version: '3.9'
services:
  db:
    image: postgres:14.3-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5431:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#volumes:
#  postgres-data: